// Copyright 2011 Boris Kogan (boris@thekogans.net)
//
// This file is part of libthekogans_util.
//
// libthekogans_util is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// libthekogans_util is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with libthekogans_util. If not, see <http://www.gnu.org/licenses/>.

#include <iostream>
#include <vector>
#include <thread>
#include <atomic>
#include <chrono>
#include <cstdlib>
#include <cassert>
#include <algorithm>
#include <CppUnitXLite/CppUnitXLite.cpp>
#include <thekogans/util/SharedAllocator.h>

using namespace thekogans::util;

// Wrapper to track thread activities
struct AllocatorStressFixture {
    // Provide a large mock shared memory pool to prevent constant ENOMEM
    std::size_t POOL_SIZE = 1024 * 1024 * 16; // 16 MB Test Buffer
    SharedAllocator* allocator = nullptr;

    void Initialize() {
        // Construct allocator layout inside aligned test block
        allocator = new SharedAllocator("foobar", POOL_SIZE, false);
    }
};

void StressTestAllocator(unsigned int worker_threads, std::chrono::seconds run_duration) {
    AllocatorStressFixture fixture;
    fixture.Initialize();

    std::atomic<bool> keep_running{true};
    std::atomic<uint64_t> total_allocs{0};
    std::atomic<uint64_t> total_frees{0};
    std::atomic<uint64_t> allocation_failures{0};

    std::vector<std::thread> workers;

    for (unsigned int i = 0; i < worker_threads; ++i) {
        workers.emplace_back([&, i]() {
            // Seed random path variations per thread thread
            unsigned int seed = i + static_cast<unsigned int>(std::time(nullptr));

            // Local tracking array to store active pointers generated by this thread
            struct AllocationRecord {
                void* ptr;
                std::size_t size;
            };
            std::vector<AllocationRecord> my_records;
            my_records.reserve(200);

            while (keep_running.load(std::memory_order_relaxed)) {

                // Strategy 1: Opportunistic Allocation (Churn Loop)
                if (my_records.size() < 150) {
                    // Alternate between tiny fields (8-16 bytes) and layout bounds (128-512 bytes)
                    std::size_t size_request = (rand_r(&seed) % 2 == 0)
                        ? (8 + (rand_r(&seed) % 24))     // Tiny block allocations
                        : (64 + (rand_r(&seed) % 448));   // Random larger allocations

                    try {
                        void* allocated_ptr = fixture.allocator->Alloc(size_request);
                        if (allocated_ptr) {
                            // 1. CRITICAL CRASH CHECK: Validate 16-byte alignment compliance
                            uintptr_t addr = reinterpret_cast<uintptr_t>(allocated_ptr);
                            if (addr % 16 != 0) {
                                std::cerr << "\n[CRITICAL ERROR] Allocator broke compliance! "
                                          << "Pointer unaligned: " << std::hex << addr << std::endl;
                                std::abort();
                            }

                            // Fill with data patterns to verify memory buffer boundaries are solid
                            std::fill_n(static_cast<uint8_t*>(allocated_ptr), 8, static_cast<uint8_t>(i));

                            my_records.push_back({allocated_ptr, size_request});
                            total_allocs.fetch_add(1, std::memory_order_relaxed);
                        }
                    } catch (...) {
                        allocation_failures.fetch_add(1, std::memory_order_relaxed);
                    }
                }

                // Strategy 2: Opportunistic Coalescing Free Loop
                if (!my_records.empty() && (rand_r(&seed) % 3 == 0 || my_records.size() >= 150)) {
                    // Pick a random index to free. This breaks sequential list mapping
                    // and violently forces the O(N) coalescing logic to look for split targets.
                    std::size_t target_idx = rand_r(&seed) % my_records.size();
                    AllocationRecord record = my_records[target_idx];

                    try {
                        fixture.allocator->Free(record.ptr, record.size);
                        total_frees.fetch_add(1, std::memory_order_relaxed);
                    } catch (...) {
                        std::cerr << "\n[CRITICAL ERROR] Free logic encountered exception!" << std::endl;
                        std::abort();
                    }

                    // Swap-and-pop to erase quickly
                    my_records[target_idx] = my_records.back();
                    my_records.pop_back();
                }

                // Yield occasionally to shuffle thread contexts
                if (rand_r(&seed) % 10 == 0) {
                    std::this_thread::yield();
                }
            }

            // Cleanup remaining leakage before thread death to verify final state logic
            for (const auto& record : my_records) {
                try {
                    fixture.allocator->Free(record.ptr, record.size);
                } catch (...) {}
            }
        });
    }

    std::cout << "Executing allocator stress test with " << worker_threads << " threads..." << std::endl;
    std::this_thread::sleep_for(run_duration);

    keep_running.store(false);
    for (auto& t : workers) {
        if (t.joinable()) t.join();
    }

    std::cout << "\n=============================================="
              << "\n Allocator Stress Session Ended Successfully"
              << "\n -> Total Successful Allocations: " << total_allocs.load()
              << "\n -> Total Successful Frees:       " << total_frees.load()
              << "\n -> Out of Memory Drops (Normal):  " << allocation_failures.load()
              << "\n==============================================" << std::endl;
}

TEST (thekogans, VersionToString) {
    unsigned int cores = std::thread::hardware_concurrency();
    unsigned int test_threads = cores > 0 ? cores * 2 : 8; // Double overcommit
    // Inject a brutal 10-second churn stress test
    StressTestAllocator(test_threads, std::chrono::seconds(10));
}

TESTMAIN
